### ISSUE TITLE
How about printing nice banner

### ISSUE THREAD

**Issue by PngWnA** [starcat37/Hello-World#3]
I've read some nice library running on python : https://velog.io/@new_wisdom/Python-ASCII-art-%EB%AC%B8%EC%9E%90-%EC%B6%9C%EB%A0%A5-feat.-pyfiglet

It would be great to print banner when the python script is executed.

**Comment by starcat37** [comment]
I imported pyfiglet to print-Hello.py, but I'm afraid I don't know how to add things about pip installation.
Do I need to make new package (something include'__init__.py' or etc) or something other in this situation?

**Comment by PngWnA** [comment]
If you want to specify that `pyfiglet` should be installed, I'll make an example PR

**Comment by susemeee** [comment]
https://pypi.org/project/art/ is another library of this kind.
