### ISSUE TITLE
Using pytest to test the program

### ISSUE THREAD

**Issue by susemeee** [starcat37/Hello-World#6]
Though making a test for printing `hello world` is a trivial task, getting used to code testing is a pretty important thing for coding / maintaining the code. Testing the code makes program much more stable.

In a Python world, developers mainly use [pytest](https://docs.pytest.org/en/6.2.x/) library for testing the code.

You can assume a situation, and make some logic for that, and also make a test code for that.

**Comment by starcat37** [comment]
I forgot to answer, thank you for the information! I'll use it when I add a new feature,
